[package]
authors = ["Victor Koenders <victor.koenders@gmail.com>"]
edition = "2018"
name = "orm_derive"
version = "0.1.0"

[dependencies]
quote = "0.6.10"
proc-macro2 = "0.4.24"

[dependencies.syn]
features = ["full"]
version = "0.15.23"

[lib]
proc_macro = true
